version: '3.2'
services:
    database:
        image: mariadb/server
        environment:
            MYSQL_DATABASE: "directus"
            MYSQL_USER: "directus"
            MYSQL_PASSWORD: "directus"
            MYSQL_ROOT_PASSWORD: "directus"
        ports:
            - "3306:3306"
        networks:
            - directus

    cache:
        image: redis:6
        networks:
            - directus
        ports:
            - 6379:6379

    directus:
        image: directus/directus:v9.0.0-rc.22
        ports:
            - 8055:8055
        networks:
            - directus
        environment:
            KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
            SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

            DB_CLIENT: 'mysql'
            DB_HOST: 'database'
            DB_PORT: '3306'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: 'false'
            CACHE_STORE: 'redis'
            CACHE_REDIS: 'redis://cache:6379'
            
            DIRECTUS_ADMIN_EMAIL: "directus@example.com"
            DIRECTUS_ADMIN_PASSWORD: "directus"

networks:
    directus:
 
